
close all;
clc;
clear;
Database_Name='FingerPrint_Synthetic_01_01';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_01_02';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_01_03';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_02_01';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_02_02';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_02_03';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_03_01';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_03_02';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

Database_Name='FingerPrint_Synthetic_03_03';
Test_Linear_Classifier_Learn_Fingerprint_Parameters

