function [average_hamming,average_runtime,hamming] = Hamming_Database_Fingerprint(Database_Test,Wxy,Wa,Wtb,display_flag,num_test_graphs)
    
% This function measures the average hamming distance (dissimilarity of mappings)
% between the ground truth correspondence and a correspondence generated by
% the Bipartite algorithm (using the degree centrality) for all registers of the
% Test set. It also measures the average runtime for each correspondence
% generation and comparison

%     for k=1: size(Database.Test,2)
%         Xmean=mean(Database.Test{1,k}.Graph.Nodes(:,1));
%         Ymean=mean(Database.Test{1,k}.Graph.Nodes(:,2));
%         Database.Test{1,k}.Graph.Nodes(:,1)=Database.Test{1,k}.Graph.Nodes(:,1)-Xmean;
%         Database.Test{1,k}.Graph.Nodes(:,2)=Database.Test{1,k}.Graph.Nodes(:,2)-Ymean;
%     end
Database.Test=Database_Test;
   
    hamming = [];
    number_of_test=0;
    total_runtime=0;
    if num_test_graphs==0
        num_test_graphs=length(Database.Test);
    end
    for i = 1:num_test_graphs
        %display(floor(100*i/num_test_graphs));
        currentElem = Database.Test{i};
        G1 = currentElem.Graph;
        for j = 1:length(currentElem.Correspondences)
                %[i j]
                G2 = Database.Test{currentElem.Correspondences{j}.InputGraph}.Graph;
                idealMapping = currentElem.Correspondences{j}.Mappings;
                        tic
                        [~,automaticMapping] = Fingerprint_Matching(G1.Nodes,G2.Nodes,Wxy,Wa,Wtb,display_flag);
                        num_coincidences=sum((automaticMapping - idealMapping)==0);
                        num_assigned=sum(idealMapping~=-1);
                        hamming(end + 1) = 1-num_coincidences/num_assigned;
                        runtime=toc;
                        total_runtime=total_runtime+runtime;
                        number_of_test=number_of_test+1;
        end
    end
    average_hamming = mean(hamming);
    average_runtime=total_runtime/number_of_test;
    %disp('Hamming done');
end